version: '3.8'
services:

  docker-mysql:
    image: mysql:debian
    restart: always
    ports:
      - "3306:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=messageApp

  springboot-container:
    image: docker-spring
    build:
      context: ./
      dockerfile: -Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/messageApp
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - "8080:8080"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      port: 5672
      username: guest
      password: guest
    ports:
      - "5672:5672"
      - "15672:15672"
